---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lnet-configuration
spec:
  selector:
    matchLabels:
      name: lnet-configuration
  template:
    metadata:
      labels:
        name: lnet-configuration
    spec:
      nodeSelector:
        kmm.node.kubernetes.io/openshift-kmm.lnet.ready: 
      hostNetwork: true
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccount: kmm-operator-module-loader
      serviceAccountName: kmm-operator-module-loader
      containers:
      - command:
        - sleep
        - infinity
        image: "image-registry.openshift-image-registry.svc:5000/openshift-kmm/lustre-client-moduleloader:5.14.0-284.25.1.el9_2.x86_64"
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - lnetctl lnet configure;
                  lnetctl net add --net tcp --if br-ex # change interface according to your cluster
          preStop:
            exec:
              command:
                - /bin/sh
                - -c
                - lnetctl lnet unconfigure && lustre_rmmod && yum remove -y lustre-client kmod-lustre-client && rm -rf /opt/lib/modules/$(uname -r)/extra/lustre-client
        name: lnet-configuration
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          runAsUser: 0
          seLinuxOptions:
            type: spc_t
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

