apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: lnet
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: libcfs
        dirName: /opt
        # parameters:
        #   - cpu_npartitions=20
        modulesLoadingOrder:
          - libcfs
          - lnet
          - ksocklnd

      imagePullPolicy: Always

      kernelMappings:  # At least one item is required
        # For any other kernel, build the image using the Dockerfile in the my-kmod ConfigMap.
        - regexp: '^.+$'
          containerImage: "image-registry.openshift-image-registry.svc:5000/openshift-kmm/lustre-client-moduleloader:${KERNEL_FULL_VERSION}"
          build:
            baseImageRegistryTLS:
              insecure: false
              insecureSkipTLSVerify: false
            dockerfileConfigMap:
              name: lustre-ci-dockerfile
          registryTLS:
            insecure: false
            insecureSkipTLSVerify: false

  selector:
    node-role.kubernetes.io/worker: ""
