apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: lnet
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: libcfs
        dirName: /opt
        parameters:
          - cpu_npartitions=20
        modulesLoadingOrder:
          - libcfs
          - lnet
          - ksocklnd

      imagePullPolicy: Always

      kernelMappings:  # At least one item is required
        # For any other kernel, build the image using the Dockerfile in the my-kmod ConfigMap.
        - regexp: '^.+$'
          containerImage: "image-registry.openshift-image-registry.svc:5000/openshift-kmm/lustre-client-moduleloader:${KERNEL_FULL_VERSION}-mofed"
          build:
            buildArgs:
              - name: MOFED_VERSION
                value: "26.07-0.7.7.0"
              - name: DOCA_IMAGE_TAG
                value: "doca3.5.0-26.07-0.7.7.0-0-rhel9.6-amd64"
            baseImageRegistryTLS:
              insecure: false
              insecureSkipTLSVerify: false
            dockerfileConfigMap:
              name: lustre-ci-dockerfile-mofed
          registryTLS:
            insecure: false
            insecureSkipTLSVerify: false

  selector:
    node-role.kubernetes.io/worker: ""

