# kubectl apply -f examples/snapshot-from-encrypted-dynamic.yaml
#
# ------------------------------------------------
# Exaxscaler CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exascaler-csi-file-driver-pvc-from-encrypted-snapshot-1
spec:
  storageClassName: exascaler-csi-file-driver-sc-1
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: snapshot-pvc-crypt-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume-from-encrypted-snapshot
spec:
  securityContext:
    runAsUser: 1001
  containers:
    - image: nginxinc/nginx-unprivileged
      imagePullPolicy: IfNotPresent
      name: nginx
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do echo $(date) > /data/timefile; sleep 5; sync; done;" ]
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: exascaler-csi-file-driver-data
  volumes:
    - name: exascaler-csi-file-driver-data
      persistentVolumeClaim:
        claimName: exascaler-csi-file-driver-pvc-from-encrypted-snapshot-1
        readOnly: false
