# --------------------------------------
# Exascaler CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: exascaler-csi-file-driver-sc-2
provisioner: exa.csi.ddn.com
allowVolumeExpansion: true
parameters:
  projectId: "100001"           # Points to a project id to be used to set volume quota.
  exaMountUid: "1001"           # Uid which will be used to access the volume in pod. Should be synced between EXA server and clients.
  exaMountGid: "1001"           # Gid which will be used to access the volume in pod. Should be synced between EXA server and clients.
  bindMount: "false"
  volumeDirPermissions: "1750"
---

# ------------------------------------------------
# Exaxscaler CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exascaler-csi-file-driver-pvc-2
spec:
  storageClassName: exascaler-csi-file-driver-sc-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume-2
spec:
  securityContext:
    runAsUser: 1001
    # runAsGroup: 1001
    # fsGroup: 1001
  containers:
    - image: nginxinc/nginx-unprivileged
      imagePullPolicy: IfNotPresent
      name: nginx
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do echo $(date) > /data/timefile; sleep 5; sync; done;" ]
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          name: exascaler-csi-file-driver-data
    - image: nginxinc/nginx-unprivileged
      imagePullPolicy: IfNotPresent
      name: nginx-sub1
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do echo $(date) > /data/timefile; sleep 5; sync; done;" ]
      ports:
        - containerPort: 81
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          subPath: sub1
          name: exascaler-csi-file-driver-data
    - image: nginxinc/nginx-unprivileged
      imagePullPolicy: IfNotPresent
      name: nginx-sub2
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do echo $(date) > /data/timefile; sleep 5; sync; done;" ]
      ports:
        - containerPort: 82
          protocol: TCP
      volumeMounts:
        - mountPath: /data
          subPath: sub2
          name: exascaler-csi-file-driver-data
  volumes:
    - name: exascaler-csi-file-driver-data
      persistentVolumeClaim:
        claimName: exascaler-csi-file-driver-pvc-2
        readOnly: false
