# --------------------------------------
# Exascaler CSI Driver - Storage Class
# --------------------------------------

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: exascaler-csi-file-driver-sc-exa1
provisioner: exa.csi.ddn.com
allowVolumeExpansion: true
parameters:
  configName: "exa1"
---

# ------------------------------------------------
# Exaxscaler CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exascaler-csi-file-driver-pvc-exa1
spec:
  storageClassName: exascaler-csi-file-driver-sc-exa1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
