
# ------------------------------------------------
# Exaxscaler CSI Driver - Persistent Volume Claim
# ------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exascaler-csi-file-driver-pvc-block-from-snapshot
spec:
  storageClassName: exascaler-csi-file-driver-sc
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
    name: snapshot-test # snapshot created by ./snapshot-from-raw-dynamic.yaml
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 11Gi
---

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume-from-snapshot
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      securityContext:
        privileged: true
      ports:
        - containerPort: 80
          protocol: TCP
      volumeDevices:
        - devicePath: /dev/sdc
          name: exascaler-csi-file-driver-data
  volumes:
    - name: exascaler-csi-file-driver-data
      persistentVolumeClaim:
        claimName: exascaler-csi-file-driver-pvc-block-from-snapshot
        readOnly: false
