# Take a new snapshot
#
# !!! Make sure to run nginx-persistent-volume.yaml before running this example
# !!! Make sure to run snapshot-class.yaml before running this example
#
# $ kubectl apply -f examples/snapshot-from-persistent.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-from-persistent
spec:
  volumeSnapshotClassName: exascaler-csi-snapshot-class
  source:
    persistentVolumeClaimName: exascaler-csi-file-driver-pvc-nginx-persistent
