# Create a new snapshot class

# $ kubectl apply -f examples/snapshot-class-encrypted.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: exascaler-csi-snapshot-class-encrypted
driver: exa.csi.ddn.com
deletionPolicy: Delete
parameters:
  snapshotUtility: tar
  snapshotFolder: csi-snapshots
  # dtarPath: /opt/ddn/mpifileutils/bin/dtar
  snapshotMd5Verify: "false"
  encryption: "true"
  csi.storage.k8s.io/snapshotter-secret-name: exa-csi-sc1
  csi.storage.k8s.io/snapshotter-secret-namespace: default
