apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: exa-csi-metrics-exporter-leader-election
  namespace: default
spec:
  holderIdentity: ""
  leaseDurationSeconds: 15
  renewTime: null
  acquireTime: null
  leaseTransitions: 0
