apiVersion: v1
kind: Service
metadata:
  name: exa-csi-metrics-exporter
  namespace: default
  labels:
    app: exa-csi-metrics-exporter
spec:
  type: ClusterIP
  ports:
    - port: 32666
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: exa-csi-metrics-exporter
