apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exa-csi-metrics-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: "9200" # Ensure this matches exporter port
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: exa-csi-metrics-exporter
