apiVersion: v1
kind: Secret
metadata:
  name: exa-csi-kmip-secret-with-endpoint
type: Opaque
stringData:
  KMIP_ENDPOINT: "10.204.40.223:5696"
  KMIP_TLS_MIN_VERSION: "1.2"
  KMIP_TLS_MAX_VERSION: "1.2"
  KMIP_CIPHER_SUITES_SECURE: "false"
  KMIP_CIPHER_SUITES_INSECURE: "true"
  KMIP_UNIQUE_IDENTIFIER: "1"
  KMIP_SERVER_NAME: "localhost"
  KMIP_CLIENT_CERT: |
    -----BEGIN CERTIFICATE-----
    MIIDSTCCAjGgAwIBAgIUEhsfFl2L18CW3t9891auo8a1LaYwDQYJKoZIhvcNAQEL
    BQAwEjEQMA4GA1UEAwwHS01JUCBDQTAeFw0yNjA3MDYxMjEzNDVaFw0zMTA3MDUx
    MjEzNDVaMBExDzANBgNVBAMMBmNsaWVudDCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAMGwLnbh6W+xa2FbLVBURPxSbXAj7HTd7Yd5EC4Gre3zpYLTPczo
    S2e8YqjcKzxU/lx+xUBjic2DRC8+qlw8yjOmwPsc1f8hv+73/FXx5DDoc8CFAi4F
    aaj3SUo35p2WXDrAQHlybOKRxPeudhopvgWNmNPF8cd8mLBmgAYWFUxogCjIqy9R
    RIquNuDics0M8qemwGq6mXUzmji4w06ylLfSEiY9StcKmyiCHFfSLdzQ6rideETi
    NIg6IC1LZRmxRJHM5aV7RKpKiwhQlhdOt2zzEsulZt88hSDjdDFsOaRoa7KDVlgC
    5qcU9mwQM87anNI+0+CXXTq4t1mU928s00UCAwEAAaOBlzCBlDAJBgNVHRMEAjAA
    MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDAjAiBgNVHREEGzAZ
    ggZjbGllbnSCCWxvY2FsaG9zdIcECswo3zAdBgNVHQ4EFgQUIlPOq9rajizfQdJz
    1IAHeFxyvAcwHwYDVR0jBBgwFoAUylVyLrERswLbayKDGnWOC2GH0VowDQYJKoZI
    hvcNAQELBQADggEBADQrAEhd5ynH5ztrNndgxjcdXExaIldOId1Hf6YJRq223xxM
    eTQNv6z18rqH8z3icUwISWfdqgqFPostqC/VBtZcr2U4LMCWFk+dhRZt2bSQ3mby
    3oDa+LOKlyDHjzW7WAmRutKxlWpca4sbUsSxndbKNV8xMAJ06nLLV3UtHy2/7sUQ
    UxIujqxBhWDMYhlzCH7GAIXtQtDMJiJjSHOxmo/Fj7ALYzNk4OXd7f+MYDUQ3uHR
    DjFV/Yf1UPSld00hGh25Y4FnBS3h85qU3IWUE5d2YNqCZqzT0wn4680TCZ06L4CD
    26zSt1+nM7RplEKm/nHuNhFARRnfmlf/iAfat1s=
    -----END CERTIFICATE-----
  KMIP_CLIENT_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBsC524elvsWth
    Wy1QVET8Um1wI+x03e2HeRAuBq3t86WC0z3M6EtnvGKo3Cs8VP5cfsVAY4nNg0Qv
    PqpcPMozpsD7HNX/Ib/u9/xV8eQw6HPAhQIuBWmo90lKN+adllw6wEB5cmzikcT3
    rnYaKb4FjZjTxfHHfJiwZoAGFhVMaIAoyKsvUUSKrjbg4nLNDPKnpsBqupl1M5o4
    uMNOspS30hImPUrXCpsoghxX0i3c0Oq4nXhE4jSIOiAtS2UZsUSRzOWle0SqSosI
    UJYXTrds8xLLpWbfPIUg43QxbDmkaGuyg1ZYAuanFPZsEDPO2pzSPtPgl106uLdZ
    lPdvLNNFAgMBAAECggEAEK6IafPOI7EPswxjzDnd0S+WPmTRrkUY+qSKKLSpkUd9
    V1WzSm0tZWtbwfhofuNBHx1KBuAr07f9DOakTJptveIcV+RlZ/pzqfTQ1mQlh7LV
    mVy7UdRkg8l8lfhXk/YJzoOVagBZcXAlm0F66Yjz1U2bPo4bY1ePXQ4O87c+MVze
    ZAIO0y+mkNGIaPlhMNRbCSWzJZyK904QlaBvRNT9fJpceXKZySifdhchmV9jSLIa
    6vZa6a8HCUq5BcxfNf60qhnoNT6WkcJYN9ONHQooR+i/QCmHAjmK6JdVTJUVv/B0
    mTQd6miehxAWKgTnwKVItrg8SO1/LIQAV9WYNG9kxwKBgQDihK6E3XWkpHqsKXSY
    IplvZTf8jZ8LQoW+A+ywD31bzxnVWqFoMsYacGKFO/XRuTOArBvT2YNzcchpGN6K
    LH541tuU5dxUd9kmQseJzyzokoXe7oJ1a7rE/2/+X4gUrxvZ6+aKiC7RG3mgHg4k
    4/l0dP8t1Lb43sXVHW+Ds99KZwKBgQDa5aQORWjMwXACymWGNRiPxuxhy2NqSNsV
    QLOiWVe43u4dSHb6tns3giXolj+zVAM0tan9fiBtk6HA2kN99QaXWvKpef08yLRK
    qac2BqD3PON6cEZJ7NlM1cRgZN2e+1JlTJP9+Nl2JA8GS7EcqExhcSN70ISowJTC
    FiR/dEwBcwKBgBYUQL6Kp5Dox1xInijGFpaZEx/23e3HCio/T67Jk7qDMU1ujBUP
    /edN1QyPj6JlnvOH0x6PMRTrnlFAL1DgjWNR7g1RamyBUhU8pR51pzb0MUBNl0HC
    wm25SD1PKoB5oQlYyRvvskCHoQ9OXqqR3hrP3J+nAD652Caxu9Dmk3k5AoGAH/Nx
    FNwwxeJeVSnx07sgUKw6iLPFWRg1Uk7VaZcc5NE1dHTFWScVqS6IFgEIX0aeCS2T
    GHs2hIgODjZNr676PVF7Jh22Rw8MsfE9hPdGu4/ZrF+DAvtdZIe3WFKgvrn0dvDM
    kT+njkUJJGQcABDYxUhcY5A2LOOfUw0kWq5BAd0CgYEAip+I0W71M+v9Dct6ZMDk
    I7Dkhll0/Q4tK3s9MI0ESazhjH+9z4LdUZ6QGlMVqaGTkbk2cG7D8fQPAYdwTcaW
    MZBbuUU6RpZLOleEvP3iTJvLC1s9QPI42pjzI9qTKtjwR1liZY3Dud5msyiCsiuf
    S9xWTwtazL7Q/mnOJ54rFvg=
    -----END PRIVATE KEY-----
  KMIP_CA_CERT: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIUXp654H76eE/eDW55e1GYhk2yHicwDQYJKoZIhvcNAQEL
    BQAwEjEQMA4GA1UEAwwHS01JUCBDQTAeFw0yNjA3MDYxMjA1MzFaFw0zMTA3MDUx
    MjA1MzFaMBIxEDAOBgNVBAMMB0tNSVAgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDG3ICAZOBPSWEzAt2ZPVWInAQjxciGY5rW762a6qbtvXqK3/vH
    DGvpJTX9setlLQFeGzeUKuMM8sJBjoJ7YVvGhlx9O6/Hj6YUATuiUIpV26ewAp7A
    0wjrbzXKUg0Yg5lr592CSM9wZjyO5Ar7Zsv79jMVQgT7ZGfVnlUd0deip2WishU6
    oq/nLAxpqWYX5Z06dLsZONXiEkG+UoZdJeDOZke3JzWt6swEFS3D4kemFrNsUCRJ
    BFle2REFLGJtVEVBf7RIRCOke6fyu3ZRUP/ceqT71TXZUO3yfGNGpkqa7sgh4LyS
    D0jlEHXTwjQ+Sl0fG3xFhSpMzUQluiebQT95AgMBAAGjUzBRMB0GA1UdDgQWBBTK
    VXIusRGzAttrIoMadY4LYYfRWjAfBgNVHSMEGDAWgBTKVXIusRGzAttrIoMadY4L
    YYfRWjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCd2Ap/sD0b
    uW0QAeamCgnnElpmndIs+x4EjWJLWQWm0dknEzTXxVayVroI36xKcgmBh/6Md04A
    xR4pJ7Qd2mB/J1+Ts1hdAoesI0sY4ELfe3k9ZvuowGL52wJvhbkbyNBZVUSeJ/vB
    4r3RYprrS/BcdBje0EnArLBNKPncRuJQYddVwH6rVE8TKtc9fy8Ki3O9cRzeL1Ua
    cqDRTaOznoIZOULht6mFJnXFlnnOktZFg2c+c0MpOtXi6vp2bFDa53HjP5J0EpTC
    ivoYjLIRARbRQaNDb9Kz8mQnv6mQrMN1XQlE//YjRC+luywtgpKkMD5e4cB9c2Tt
    DQYhuyFxYqSO
    -----END CERTIFICATE-----
