{{- if .Values.metrics.enabled }}
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: exa-csi-metrics-exporter-leader-election
  namespace: {{ .Values.metrics.exporter.namespace }}
spec:
  holderIdentity: ""
  leaseDurationSeconds: 15
  renewTime: null
  acquireTime: null
  leaseTransitions: 0
{{- end }}
