{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: exa-csi-metrics-exporter
  namespace: {{ .Values.metrics.exporter.namespace }}
  labels:
    app: exa-csi-metrics-exporter
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.exporter.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: exa-csi-metrics-exporter
{{- end }}
